### ISSUE TITLE
Missing 'YJango.jpg'

### ISSUE THREAD

**Issue by CBrauer** [YJango/TFRecord-Dataset-Estimator-API#1]
HI,

You did not include 'YJango.jpg' in you repo.

---> 26 img=mpimg.imread('YJango.jpg')
     27 tensors = np.array([img,img,img])
     28 # show image
[Errno 2] No such file or directory: 'YJango.jpg'

Charles

**Comment by YJango** [comment]
I've included it now.
'YJango.jpg'  is my profile picture, you can use any pic you like

**Comment by CBrauer** [comment]
Thanks.  You do good work.
